### 프로파일 설정을 하지 않으면 기본적으로 Local 로 설정된다.
spring.profiles.active: local

server:
  port: 8090
  error: # Whitelabel Error Page config
    include-exception: true
    include-stacktrace: always

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:h2:file:~/work/tool/h2db/testdb;MODE=MySQL
    url: jdbc:log4jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        show_sql: true # logback 과 중복되어 주석처리함.
        format_sql: true
        hbm2ddl:
          auto: create
#        resource.beans.container: org.springframework.orm.hibernate5.SpringBeanContainer # JPA Listener 에서 스프링 Bean DI 하기 위한 설정. (hibernate 5.3+, spring 5.1+)
#        session_factory.session_scoped_interceptor: EntityInterceptor 적용 (hibernate 5.2+)
    open-in-view: false
  h2:
    console:
      enabled: true

#  batch:
#    jdbc:
#      table-prefix: PRODUCT_BATCH_
#      schema: classpath:/org/springframework/batch/core/schema-h2.sql # 스키마 위치 설정
#      initialize-schema: always

management:
  endpoints:
    web:
      exposure:
        include: "*" # 모든 actuator기능 open

logging.level:
  org.springframework:
    web: debug
#    orm.jpa: trace # 트랜잭션 로깅
  jdbc: off
  jdbc.sqltiming: info # SQL문과 해당 SQL을 실행시키는데 수행된 시간 정보(milliseconds). sqlonly 설정 포함
#  jdbc.resultsettable: info # 조회 결과
#  jdbc.connection: debug # open&close 정보
#  jdbc.resultset: off # ResultSet을 포함한 모든 JDBC 호출 정보
#  jdbc.audit: off # ResultSet을 제외한 모든 JDBC 호출 정보

# batch
#spring.batch.job.names: ${job.name:NONE} # 수행할 job 이름. run arguments 로 입력받는다. ex) --job.name=syncShowInAppJob requestDate=20210731
