### logging
logging:
  level:
    org:
      springframework.orm.jpa: debug
      hibernate:
        type.descriptor: trace

### JPA
spring.jpa:
  properties:
    hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl:
        auto: update

### database
database:
  datasource-write:
    jdbcUrl: jdbc:mariadb://mariadb:3306/myschema?allowPublicKeyRetrieval=true&useSSL=false
  datasource-read:
    jdbcUrl: jdbc:mariadb://mariadb:3306/myschema?allowPublicKeyRetrieval=true&useSSL=false&profileSQL=true&logger=Slf4JLogger
