### logging
logging:
  level:
    org:
      springframework.orm.jpa: debug

### JPA
spring.jpa:
  properties:
    hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl:
        auto: update
